### PR TITLE
Added CSS vars for dropdown-trigger icon

### PR DESCRIPTION
**Pull request by JaySunSyn**
In order to be able to change the share icon size.

Many thanks for this element!

### CODE REVIEW

**Comment by MacTheZazou** [comment]
Thank you for this PR! Can you modify the doc with a new PR? I'm away from home for 3-4 days...

@JaySunSyn

**Comment by JaySunSyn** [comment]
Sure, done, thanks!

**Comment by MacTheZazou** [comment]
Thank you a lot!

**Comment by MacTheZazou** [comment]
@JaySunSyn I just modified all the css var names. You should upgrade to 2.0.0.

**Pull request merged**
